export interface NewsAPI {
  status: string;
  totalResults: number;
  articles: Article[];
}

export interface Article {
  source: Source;
  author: null | string;
  title: string;
  description: string;
  url: string;
  urlToImage: string;
  publishedAt: string;
  content: null | string;
}

export interface Source {
  id: null | string;
  name: string;
}

// Generated by https://quicktype.io

export interface FilteredArticles {
  status:  string;
  sources: FilteredSource[];
}

export interface FilteredSource {
  id:          string;
  name:        string;
  description: string;
  url:         string;
  category:    Category;
  language:    Language;
  country:     string;
}

export enum Category {
  Sports = "sports",
}

export enum Language {
  En = "en",
  Es = "es",
  Fr = "fr",
}
